import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,CheckCircle2,ChevronDown,Clock,FileText,Lightbulb,Printer,Save} from 'lucide-react';
import {getApi,requestId,type RecordData as D} from './api';
import {Diagram,Empty,Prose} from './components';
import {Notebook} from './App';
import {guideProgress,ResourceCards} from './Learn';
import Walkthrough from './Walkthrough';
import './illustrated.css';

type Props={id:string;focus?:string;sectionId?:string;state:D;perform:(name:string,data?:D)=>Promise<any>;notify:(message:string,error?:boolean)=>void};
export default function GuideReader({id,focus,sectionId,state,perform,notify}:Props){
 const [guide,setGuide]=useState<D|null>(null),[path,setPath]=useState<D|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<D|null>(null),[savedWork,setSavedWork]=useState('');
 const storageKey=`form-guide-work-${id}`;
 const [work,setWork]=useState<D>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||(state.drafts||[]).find((item:D)=>item.targetId===`guide:${id}`)?.text||'{"exercise":"","answers":{}}');}catch{return {exercise:'',answers:{}};}});
 const position=useRef(localStorage.getItem(`form-guide-position-${id}`)||guideProgress(state,id).position||'');
 const progress=guideProgress(state,id),answers=work.answers||{};
 useEffect(()=>{let live=true,interacted=false;let restoreTimer:ReturnType<typeof setTimeout>|undefined;const targetAtOpen=sectionId||(focus==='practice'?'try-it':focus==='review'?'takeaway':position.current);const takeControl=()=>{interacted=true;};for(const event of ['pointerdown','wheel','touchstart','keydown'])window.addEventListener(event,takeControl,{passive:true});getApi(`guides/${encodeURIComponent(id)}`).then(async data=>{if(!live)return;setGuide(data);try{await perform('open_guide',{guideId:id});}catch{/* Shared notification. */}if(targetAtOpen)restoreTimer=setTimeout(()=>{if(live&&!interacted)document.getElementById(targetAtOpen)?.scrollIntoView();},300);}).catch(err=>{if(live)setError(err.message);});getApi('learning-path').then(data=>{if(live)setPath(data);}).catch(()=>{});return()=>{live=false;clearTimeout(restoreTimer);for(const event of ['pointerdown','wheel','touchstart','keydown'])window.removeEventListener(event,takeControl);};},[id]);
 useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify(work));},[work,storageKey]);
 useEffect(()=>{if(!guide)return;const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(visible[0]){position.current=visible[0].target.id;localStorage.setItem(`form-guide-position-${id}`,position.current);}}, {rootMargin:'-10% 0px -65% 0px',threshold:0});document.querySelectorAll('.guide-section[id]').forEach(section=>observer.observe(section));return()=>observer.disconnect();},[guide,id]);
 const run=async(task:()=>Promise<void>)=>{setBusy(true);try{await task();}catch{/* Shared notification. */}finally{setBusy(false);}};
 const saveProgress=async(extra:D)=>{await perform('save_guide_progress',{guideId:id,revision:guideProgress(state,id).revision||0,position:position.current,...extra});};
 const saveWork=async()=>{const draft=(state.drafts||[]).find((item:D)=>item.targetId===`guide:${id}`);await perform('save_draft',{targetId:`guide:${id}`,revision:draft?.revision||0,text:JSON.stringify(work)});setSavedWork(JSON.stringify(work));notify('Your practice work is saved on this computer.');};
 const updateAnswer=(questionId:string,value:any)=>setWork({...work,answers:{...answers,[questionId]:value}});
 if(error)return <Empty title="This lesson could not open"><p>{error}</p><a className="button primary" href="#learn">Return to your learning path</a></Empty>;
 if(!guide)return <div className="loading"><span className="spinner"/> Opening your lesson…</div>;
 const sections:D[]=guide.sections||[],diagrams:D[]=guide.diagrams||[],questions:D[]=guide.questions||[];
 const allDays=(path?.weeks||[]).flatMap((week:D)=>(week.days||[]).map((day:D)=>({...day,week:week.number}))),guideDays:D[]=allDays.filter((day:D,index:number,array:D[])=>day.guideId&&array.findIndex(item=>item.guideId===day.guideId)===index);
 const currentIndex=guideDays.findIndex(day=>day.guideId===id),next=guideDays[currentIndex+1],previous=guideDays[currentIndex-1];
 const resourceIds=allDays.filter((day:D)=>day.guideId===id).flatMap((day:D)=>day.resourceIds||[]),resources=(path?.resources||[]).filter((resource:D)=>resourceIds.includes(resource.id));
 const feedback=result?.results||result?.feedback||[];
 return <div className="guide-reader"><div className="reader-top"><a className="back-link" href={`#learn?week=${guide.week||1}`}><ArrowLeft size={15}/> Back to week {guide.week||1}</a><div className="button-row"><button className="button subtle compact" onClick={()=>window.print()}><Printer size={14}/> Print chapter</button><button className={`icon-button ${progress.bookmarked?'bookmarked':''}`} disabled={busy} aria-label={progress.bookmarked?'Remove lesson bookmark':'Bookmark this lesson'} onClick={()=>void run(()=>saveProgress({bookmarked:!progress.bookmarked}))}><Bookmark size={18} fill={progress.bookmarked?'currentColor':'none'}/></button><button className="button subtle compact" disabled={busy} onClick={()=>void run(async()=>{await saveProgress({});notify('Your place in this lesson is saved.');})}><Save size={14}/> Save my place</button></div></div>
 <header className="guide-header"><p className="eyebrow">WEEK {guide.week||1} · {guide.level||'BUILD YOUR UNDERSTANDING'}</p><h1>{guide.title}</h1><p className="guide-summary">{guide.summary}</p><div className="guide-meta"><span><Clock size={15}/>{guide.minutes||40} minutes</span><span><BookIcon/>{progress.completedAt?'You’ve studied this lesson':'Read, try, and explain'}</span><span>Saved on your computer</span></div></header>
 <div className="guide-layout"><article className="guide-body"><section className="guide-objectives guide-section" id="understand"><p className="eyebrow">WHAT YOU’LL UNDERSTAND</p><ul>{(guide.objectives||[]).map((objective:string,index:number)=><li key={index}><Check size={16}/><span>{objective}</span></li>)}</ul></section>
 {(guide.terms||[]).length>0&&<section className="guide-terms guide-section" id="words"><h2>A few words we’ll use</h2><p>No need to memorize these. Come back whenever you need them.</p><dl>{guide.terms.map((term:D)=><div key={term.term}><dt>{term.term}</dt><dd>{term.definition}</dd></div>)}</dl></section>}
 {(guide.retrieval||[]).length>0&&<details className="guide-recall"><summary><RotateIcon/> Before you begin: a quick look back <ChevronDown size={14}/></summary><ul>{guide.retrieval.map((item:string,index:number)=><li key={index}>{item}</li>)}</ul><p>It’s fine if you’re unsure. The lesson will help you connect the ideas.</p></details>}
 {sections.map((section,index)=>{const teaching=<><Prose text={section.markdown||section.content}/>{diagrams.filter(diagram=>diagram.sectionId===section.id).map(diagram=><Diagram key={diagram.id} diagram={diagram}/>)}{(guide.walkthroughs||[]).filter((story:D)=>story.sectionId===section.id).map((story:D)=><Walkthrough key={story.id} story={story}/>)}</>;return <section className="guide-section guide-teaching" id={section.id||`part-${index+1}`} key={section.id||index}><div className="guide-section-heading"><span>{String(index+1).padStart(2,'0')}</span><h2>{section.title}</h2></div>{section.kind==='timed-change'?<details className="guide-timed-change"><summary>Open this change when your timer reaches 25 minutes <ChevronDown size={14}/></summary>{teaching}</details>:teaching}</section>;})}
 {diagrams.filter(diagram=>!diagram.sectionId||!sections.some(section=>section.id===diagram.sectionId)).map(diagram=><Diagram key={diagram.id} diagram={diagram}/>)}
 {guide.exercise&&<section className="guide-section guide-exercise" id="try-it"><p className="eyebrow">YOUR TURN · {guide.exercise.minutes||10} MINUTES</p><h2>Try it yourself.</h2><Prose text={guide.exercise.prompt}/><label className="guide-answer-label" htmlFor="guide-exercise-answer">Your explanation or sketch</label><textarea id="guide-exercise-answer" rows={7} placeholder="Use your own words. A few sentences, a list of steps, or a simple sketch description is enough." value={work.exercise||''} onChange={event=>setWork({...work,exercise:event.target.value})}/>{(guide.exercise.rubric||[]).length>0&&<details className="guide-good-answer"><summary>What to include <ChevronDown size={14}/></summary><ul>{guide.exercise.rubric.map((item:string,index:number)=><li key={index}>{item}</li>)}</ul></details>}<div className="guide-work-footer"><span>{savedWork===JSON.stringify(work)?'Your work is saved.':'Your draft recovers in this browser. Save to keep it in your learner record.'}</span><button className="button secondary compact" disabled={busy} onClick={()=>void run(saveWork)}><Save size={14}/> Save my work</button></div>{guide.exercise.solution?<details className="guide-example-answer"><summary>Compare with an example answer <ChevronDown size={14}/></summary><Prose text={guide.exercise.solution}/></details>:<button className="text-link" disabled={busy} onClick={()=>void run(async()=>{const revealed=await perform('reveal_guide',{guideId:id});setGuide(revealed);})}>Show an example answer <ArrowRight size={14}/></button>}</section>}
 {questions.length>0&&<section className="guide-section guide-quiz" id="check-understanding"><p className="eyebrow">A SMALL CHECK, NOT A TEST TO FEAR</p><h2>Does the idea make sense?</h2><p>Try these questions. The explanation matters more than getting it right the first time.</p><form onSubmit={event=>{event.preventDefault();void run(async()=>{setResult(await perform('submit_guide_quiz',{guideId:id,answers,idempotencyKey:requestId()}));});}}>{questions.map((question,index)=><fieldset className="question" key={question.id}><legend><span>{index+1}</span>{question.prompt}</legend>{question.type==='choice'?<div className="choice-list">{(question.options||[]).map((option:string)=><label className={answers[question.id]===option?'checked':''} key={option}><input type="radio" name={`guide-${question.id}`} checked={answers[question.id]===option} onChange={()=>updateAnswer(question.id,option)}/><span>{option}</span></label>)}</div>:question.type==='numeric'?<div className="number-answer"><input type="number" step="any" required aria-label={`Your answer to question ${index+1}`} value={answers[question.id]??''} onChange={event=>updateAnswer(question.id,event.target.value===''?'':Number(event.target.value))}/>{question.unit&&<span>{question.unit}</span>}</div>:<textarea rows={4} aria-label={`Your answer to question ${index+1}`} value={answers[question.id]||''} placeholder="Explain it as if you were helping a friend understand." onChange={event=>updateAnswer(question.id,event.target.value)}/>}</fieldset>)}<div className="button-row"><button className="button primary" disabled={busy||questions.some(question=>question.type!=='open'&&(answers[question.id]===undefined||answers[question.id]===''))}>{busy?'Saving…':'Check my answers'} <ArrowRight size={15}/></button><button className="button secondary" type="button" disabled={busy} onClick={()=>void run(saveWork)}>Save my work</button></div></form>{result&&<div className="guide-feedback" role="status"><h3>{result.total?`${result.correct} of ${result.total} quick checks correct`:'Your answers are saved.'}</h3><p>Written explanations are for you to compare with the example; they do not receive an automatic score.</p>{feedback.map((item:D,index:number)=><div key={item.questionId||index}><h4>{item.correct===true?'✓ You’ve got it':item.correct===false?'Let’s look at this one':'Compare your explanation'}</h4><Prose text={item.explanation}/>{item.correct!==true&&item.answer!==undefined&&<Prose text={`**Example answer:** ${item.answer}`}/>}</div>)}</div>}</section>}
 {guide.mentalModel&&<section className="guide-section guide-recap" id="takeaway"><Lightbulb size={24}/><div><p className="eyebrow">THE ONE IDEA TO KEEP</p><Prose text={guide.mentalModel}/></div></section>}
 <section className="guide-section guide-notes" id="my-notes"><details><summary><FileText size={17}/> Keep a note in your own words <ChevronDown size={15}/></summary><Notebook state={state} targetId={`guide:${id}`} kind="note" label="My lesson notes" placeholder="The idea I want to remember…\n\nSomething I can now explain…\n\nA question I still have…" perform={perform} notify={notify}/></details></section>
 {resources.length>0&&<section className="guide-section" id="explore-more"><p className="eyebrow">OPTIONAL · WHEN YOU WANT ANOTHER EXPLANATION</p><h2>Go a little further.</h2><p>You can finish this lesson without opening these links. Videos and articles need an internet connection.</p><ResourceCards resources={resources}/></section>}
 {(guide.sources||[]).length>0&&<details className="sources-box"><summary>Sources for this lesson <ChevronDown size={15}/></summary><p>The teaching above is available offline. These links support it and are optional further reading.</p><ul>{guide.sources.map((source:D,index:number)=><li key={index}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a>{source.note&&<p>{source.note}</p>}</li>)}</ul></details>}
 <section className="guide-finish"><div><CheckCircle2 size={25}/><h2>{progress.completedAt?'A good step forward.':'Ready for the next step?'}</h2><p>{progress.completedAt?'You’ve marked this lesson as studied. Come back whenever you want a refresher.':'If you can explain the main idea in your own words, mark this lesson complete. It’s always okay to revisit it.'}</p></div><div className="button-row"><button className={`button ${progress.completedAt?'secondary':'primary'}`} disabled={busy} onClick={()=>void run(async()=>{await saveProgress({completed:!progress.completedAt});notify(progress.completedAt?'Lesson marked to revisit.':'Lesson complete. Your place in the learning path is saved.');})}><CheckCircle2 size={16}/>{progress.completedAt?'Mark to revisit':'Mark lesson complete'}</button>{next&&next.guideAvailable!==false&&<a className="text-link" href={`#guide/${next.guideId}`}>Next lesson <ArrowRight size={15}/></a>}</div></section>
 <nav className="lesson-navigation" aria-label="Beginner course lessons">{previous?<a href={`#guide/${previous.guideId}`}><ArrowLeft size={16}/><div><small>PREVIOUS LESSON</small><span>{previous.title}</span></div></a>:<span/>}<a href={`#learn?week=${guide.week||1}`}><div><small>YOUR LEARNING PATH</small><span>Return to this week’s plan</span></div><ArrowRight size={16}/></a></nav></article>
 <aside className="guide-toc"><p className="eyebrow">IN THIS LESSON</p><a href="#understand" onClick={scrollToSection}>What you’ll understand</a>{sections.map((section,index)=><a key={section.id||index} href={`#${section.id||`part-${index+1}`}`} onClick={scrollToSection}><span>{index+1}</span>{section.title}</a>)}{guide.exercise&&<a href="#try-it" onClick={scrollToSection}>Try it yourself</a>}{questions.length>0&&<a href="#check-understanding" onClick={scrollToSection}>Check your understanding</a>}<a href="#takeaway" onClick={scrollToSection}>The one idea to keep</a><div className="toc-tip"><Lightbulb size={19}/><p>Go slowly. Trace the example. Use your own words. You’re building understanding, not collecting terminology.</p></div></aside></div></div>;
}
function scrollToSection(event:React.MouseEvent<HTMLAnchorElement>){event.preventDefault();document.getElementById(event.currentTarget.getAttribute('href')!.slice(1))?.scrollIntoView({behavior:'smooth'});}
function BookIcon(){return <FileText size={15}/>;}
function RotateIcon(){return <Lightbulb size={16}/>;}
