export interface Module { id: string; title: string; phase?: string; prerequisites: string[]; exitSkill: string; [key: string]: unknown }
export interface LessonMeta { id: string; moduleId: string; title: string; priority: string; depth: string; minutes: number; type: string; prerequisites: string[]; [key: string]: unknown }
export interface Question { id: string; type: 'choice'|'numeric'|'open'; prompt: string; options?: string[]; answer?: string|number; tolerance?: number; unit?: string; explanation?: string }
export interface GuideWalkthrough {id:string;title:string;sectionId:string;intro:string;steps:{title:string;explanation:string;state:{label:string;value:string}[]}[];takeaway:string}
export interface Guide {walkthroughs?:GuideWalkthrough[];id:string;title:string;version:string;week:number;level:string;minutes:number;summary:string;objectives:string[];terms:{term:string;definition:string}[];retrieval:unknown[];sections:{id:string;title:string;markdown:string}[];diagrams:unknown[];exercise?:{prompt:string;minutes:number;rubric:unknown;solution?:string};questions:Question[];flashcards:{front:string;back:string}[];mentalModel?:string;sources?:unknown[]}
export interface Lesson extends LessonMeta { version: string; status: string; objectives: string[]; retrieval: unknown[]; sections: {id:string;title:string;markdown:string}[]; diagrams: unknown[]; exercise?: { prompt:string; minutes:number; rubric:unknown; solution?:string }; questions:Question[]; flashcards:{front:string;back:string}[]; mentalModel?:string; sources?:unknown[] }
export interface Interview { id:string;lessonId:string;title:string;aliases:string[];modeType:string;minutes:number;brief:string;clarifications:{question:string;answer:string}[];hints:string[];changes:unknown[];rubric:{id:string;label:string;weight:number}[];referenceSolution:unknown;debrief:unknown;remediation:unknown;version?:string|number;protectedLessonIds?:string[];debriefLessonId?:string }
export interface Turn { id:string;role:'candidate'|'interviewer';kind:string;text:string;at:string }
export interface InterviewSession {id:string;interviewId:string;lessonId:string;mode:'coaching'|'exam';status:'active'|'paused'|'feedback_pending'|'reviewed';revision:number;createdAt:string;updatedAt:string;startedAt:string|null;elapsedMs:number;turns:Turn[];hints:{index:number;text:string;at:string}[];feedback?:unknown;submittedAt?:string;definitionVersion?:string;definitionSnapshot?:Interview}
