import {readFileSync,writeFileSync} from 'node:fs';
export const manifest=JSON.parse(readFileSync('content/manifest.json','utf8'));
export const section=(id,title,markdown)=>({id,title,markdown});
export const choice=(id,prompt,options,answer,explanation)=>({id,type:'choice',prompt,options,answer,explanation});
export const open=(id,prompt,answer)=>({id,type:'open',prompt,answer,explanation:answer});
export const numeric=(id,prompt,answer,unit,explanation,tolerance=0.01)=>({id,type:'numeric',prompt,answer,unit,explanation,tolerance});
export const card=(front,back)=>({front,back});
export const diagram=(id,title,source,caption,steps)=>({id,title,source,caption,steps});
export const source=(title,url)=>({title,url,checked:'2026-09-29'});
export function lesson(data){writeFileSync(`content/lessons/${data.id}.json`,JSON.stringify({version:1,status:'drafted',authoredBy:'original',...data},null,2)+'\n');}
export function assessment(data){const meta=manifest.lessons.find(x=>x.id===data.lessonId);const definition={id:meta.interviewId,title:meta.title,version:1,status:'drafted',authoredBy:'original',aliases:[`L${meta.id}`,`lesson_${meta.id}`],modeType:meta.assessmentType,minutes:45,sessionMinutes:meta.minutes,rubric:manifest.rubric,...data};writeFileSync(`content/interviews/${definition.id}.json`,JSON.stringify(definition,null,2)+'\n');lesson({id:meta.id,objectives:['Clarify the guarantee and scope before designing.','Defend a mechanism with actual reasoning and failure evidence.'],retrieval:[],sections:[section('brief','Candidate brief',definition.brief),section('workflow','Saved assessment and separate debrief','Use the interview center for a saved coaching or exam attempt. The core hour reserves 45 minutes for reasoning and 15 for feedback and a focused retry plan. Ask one clarification at a time; record actual statements and artifacts. Reference reasoning is available only after answering has ended. Feedback must cite submitted evidence and identify self or AI authorship.')],diagrams:[],exercise:{minutes:45,prompt:definition.brief,rubric:['Requirements and evidence.','Mechanism and recovery.','Defended tradeoffs.'],solution:'Retrieve the protected interview debrief after submitting your attempt.'},questions:[],flashcards:[],mentalModel:'A defensible design connects the requirement to a mechanism and a falsifiable failure test.',sources:[]});}
export const standardBudget=section('schedule','Core and optional practice','Core 55 minutes: retrieval 5, explanation 18, worked trace 8, bounded exercise 10, scheduled Q1–Q3 10, comparison and cards 4. Q4–Q5 are optional extra practice. Numerical workloads and architectural examples are original teaching assumptions, not production measurements.');
