import {readFileSync,writeFileSync} from 'node:fs';
export const manifest=JSON.parse(readFileSync('content/manifest.json','utf8'));
export const section=(id,title,markdown)=>({id,title,markdown});
export const choice=(id,prompt,options,answer,explanation)=>({id,type:'choice',prompt,options,answer,explanation});
export const numeric=(id,prompt,answer,unit,explanation,tolerance=0)=>({id,type:'numeric',prompt,answer,unit,tolerance,explanation});
export const open=(id,prompt,answer,explanation=answer)=>({id,type:'open',prompt,answer,explanation});
export const source=(title,url)=>({title,url,checked:'2026-09-29'});
export function writeLesson(id,{objectives,retrieval,sections,diagrams,exercise,questions,flashcards,mentalModel,sources}){writeFileSync(`content/lessons/${id}.json`,JSON.stringify({id,version:1,status:'drafted',authoredBy:'original',objectives,retrieval,sections,diagrams,exercise:{minutes:10,...exercise},questions,flashcards:flashcards.map(c=>Array.isArray(c)?{front:c[0],back:c[1]}:c),mentalModel,sources},null,2)+'\n');}
export function diagram(title,source,caption,steps,id='mechanism'){return {id,title,source,caption,steps};}
export function writeAssessment(id,{brief,clarifications,hints,changes,referenceSolution,debrief,remediation,sources}){
const meta=manifest.lessons.find(l=>l.id===id);const interview={id:meta.interviewId,lessonId:id,title:meta.title.replace(/^\[[A-D]\]\s*/,''),aliases:[`L${id}`,`lesson_${id}`],version:1,status:'drafted',modeType:meta.assessmentType,minutes:meta.minutes,brief,clarifications:clarifications.map(([question,answer])=>({question,answer})),hints,changes,rubric:manifest.rubric,referenceSolution,debrief,remediation};
writeFileSync(`content/interviews/${interview.id}.json`,JSON.stringify(interview,null,2)+'\n');
writeLesson(id,{objectives:['Clarify the scenario and state its invariants before choosing mechanisms.','Defend a design or repair with workload and failure reasoning.','Record actual decisions and identify a focused remediation exercise.'],retrieval:remediation.map(l=>`Recall the relevant mechanism from L${l} before starting the timed attempt.`),sections:[section('brief','Candidate scenario',brief),section('workflow','Run the session and preserve evidence',`Scheduled${meta.minutes} minutes. Start ${interview.id} in the Interview center or through the MCP start_interview tool. Coaching mode permits requested hints; exam mode begins with only the candidate brief. Ask clarifying questions one at a time and save actual reasoning, calculations and diagrams as interview turns. The course engine cannot infer what happened in a separate AI chat unless it is explicitly recorded.

Use approximately5 minutes to scope,10 for requirements/estimates,15 for the main mechanism,15 for failures or a changed constraint,10 for verification and alternatives, and5 to summarize. Adjust the split to this scenario; naming assumptions and correcting them is more valuable than following a timer mechanically. Pause through the session controls when necessary so the saved timer remains meaningful.`),section('submission','End answering before comparing with references',`Save a final explanation containing the invariant, authoritative state, operation order, failure policy and a concrete acceptance test. Finish the session to close the answering phase. The engine records that submission without inventing a score. An AI evaluator must use every weighted dimension and cite exact candidate turns; offline evaluation is explicitly labeled self assessment.

Reference reasoning becomes available only after answering ends. Compare mechanisms and assumptions, not exact wording. A valid alternative needs its own tradeoff argument and boundary conditions. Record the strongest decision, the most consequential missing assumption and a bounded retry exercise. Preserve the original attempt so the retry can show what changed. A teaching score is evidence with uncertainty; it does not guarantee a hiring outcome.`)],diagrams:[diagram('From an actual attempt to a focused retry','flowchart LR\nB[Brief] --> C[Clarify]\nC --> R[Record actual reasoning]\nR --> S[Submit]\nS --> F[Evidence-based feedback]\nF --> T[Targeted retry]','The reference solution remains separate during an active or paused attempt. Saved candidate turns provide the evidence for evaluation.',['Clarify requirements.','Save decisions and calculations.','Finish without an invented grade.','Use the debrief to choose a focused retry.'])],exercise:{minutes:40,prompt:'Complete the scenario in the session notebook, including an operation/failure trace and an acceptance test.',rubric:['Defines the contract and workload.','Shows mechanisms that enforce invariants.','Handles the given failure and changed requirement.','Records concrete evidence and uncertainties.'],solution:referenceSolution},questions:[open('q1','Which requirement most affected your proposed mechanism?','Identify a real requirement from the saved attempt and connect it to a concrete design choice.'),open('q2','Which failure trace would disprove the unsafe alternative?','Give a reproducible ordering with an observable invariant violation.'),open('q3','What will you practise on the retry?','Choose a weakly supported rubric dimension and a changed-constraint exercise.')],flashcards:[['Good interview evidence?','Actual requirements, estimates, diagrams, traces and justified decisions.'],['A reference answer?','One defensible explanation under stated assumptions, not an exact-string target.'],['An uncertain outcome?','The caller lacks a result; the operation may have taken effect.'],['A useful retry?','A small changed-constraint task focused on one observed weakness.'],['A course score?','Educational AI/self assessment with uncertainty, not a hiring guarantee.']],mentalModel:'Make the guarantee concrete enough to test, then support your evaluation with what was actually submitted.',sources});
}
