import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..');
const manifest=JSON.parse(readFileSync(resolve(root,'content/manifest.json'),'utf8'));
const specs={
P1:{file:'shortener',invariant:'A code names exactly one immutable destination; successful create survives restart. Cache loss may add latency but cannot change a redirect.',requirements:['Accept only bounded HTTP(S) destinations without embedded credentials. Return a collision-safe code and a persistent redirect.','Support optional expiration; expired values must fail even when cached. Cache is derived, never authoritative.','Measure operations and skew locally. Demonstrate partition reassignment without claiming that the simulation moves durable data.'],architecture:'POST /links → validated create → SQLite unique code; GET /code → cache → SQLite fallback → 302. Rendezvous assignment is a separate deterministic partition simulation.',limits:'Single-machine SQLite, immutable links, an in-process cache, and a teaching HTTP harness. No abuse classifier, cross-node replication, account service, or distributed migration is implemented.',milestones:[
['Persistent create and redirect','Implement create/resolve with a UNIQUE code constraint. Use the injected code factory to force a collision, retry at most ten times, and prove both destinations remain distinct after opening a second service instance. Validate destination protocol before any write.','A collision overwrites an existing destination in an unsafe INSERT OR REPLACE implementation. Inject repeated identical codes; the original mapping must remain unchanged.','Persist two URLs, force a collision, reopen the database, and capture the exact redirect destinations.'],
['Cache behavior and measurement','Add cache-aside reads with metrics for DB reads, cache hits, and cache failures. Run the same redirect twice, disable the cache, then advance the fake clock exactly to expiration. Compare query counts under identical workloads before interpreting latency.','A TTL checked only at cache insertion can serve expired links. Keep absolute expiry with the cached value and evaluate on every read.','Record one DB read for two warm reads, a DB fallback during cache failure, and a not-found result at expiry.'],
['Partition movement and hotspots','Implement highest-score rendezvous assignment using SHA-256 of key plus node. Compare 1,000 keys on two nodes versus three. Identify which assignments change and explain why actual migration needs ownership epochs and read/write handoff.','Hash distribution balances distinct keys, not accesses. Repeating a viral key still concentrates requests on one owner; adding nodes alone does not split that key.','Show every moved key selects the new node; report moved fraction and distinguish the simulation from a storage migration.'],
['Evolution and evidence','Run a skewed workload with 900 requests for one key and 100 distinct requests. Explain cache placement, admission controls, destination abuse checks, and the acceptable DB fallback load. Defend a single database until measured constraints justify more state machinery.','Cache outage plus viral traffic can overload the database. State a bounded fallback policy; do not infer production throughput from this local harness.','Submit operation counters, skew table, the collision exhaustion result, and one decision record with assumptions and a rollback trigger.']
],extensions:['Add authenticated mutable destinations using versions and cache invalidation tests.','Model partition owner epochs and stale-owner rejection before implementing network distribution.']},
P2:{file:'limiter',invariant:'An atomic bucket admits at most its starting capacity plus elapsed refill; regional reservations never exceed the global allocation.',requirements:['Implement deterministic token-bucket boundaries with explicit capacity, refill rate, clock, and request cost.','Serialize shared read/refill/debit using SQLite BEGIN IMMEDIATE. Preserve per-tenant isolation.','Choose fail-open or fail-closed explicitly; report degraded decisions. Regional quotas are disjoint reservations rather than a fictional global counter.'],architecture:'tenant request → validation → atomic bucket refill/debit → allowed or retry_after. Regional design allocates conserved token ceilings before a partition occurs.',limits:'SQLite is one shared authority on one machine. Regional allocation is a static accounting model. Dynamic quota transfer, distributed clocks and an HTTP proxy are extensions.',milestones:[
['Clock and boundary behavior','Implement token refill and cost subtraction using a supplied clock. Clamp to capacity and preserve the last timestamp when time moves backward. Explain how tokens differ from a request-per-fixed-window counter.','A backward wall clock must not mint tokens later by overwriting the previous timestamp. Test half-token waits and the exact eligibility boundary.','Exhaust a capacity-two bucket, show a 0.5-second retry estimate halfway to refill, and admit exactly once after one second.'],
['Shared atomic admission','Run fifty concurrent requests against one tenant at a frozen clock and capacity ten. Read, refill, check, and update within one write transaction; report SQLite contention as distinct from an allowed request.','Separate SELECT and UPDATE transactions permit concurrent callers to spend the same tokens. Reproduce the risk conceptually and verify the transactional implementation admits exactly ten.','Capture fifty results with exactly ten admissions and forty denials. Explain what the database lock protects and how a distributed store would need equivalent atomicity.'],
['Regional quota budget','Allocate a global capacity of one hundred as EU sixty and US forty. Demonstrate that partitioned regions can enforce their portions without coordination, and identify stranded capacity when demand shifts.','Reallocating reservations before the old owner relinquishes them can temporarily double-spend. Specify an ownership epoch or conservative transfer procedure as a design extension.','Reject allocations summing above one hundred; document a regional imbalance scenario and the deliberate availability/utilization tradeoff.'],
['Load and failure defense','Inject a store outage under both policies. Fail-open preserves service access while admitting unmetered work; fail-closed protects scarce or costly resources while rejecting eligible work. Select policies separately for login defense and optional analytics.','Do not silently treat infrastructure errors as normal denials. Return a degraded marker and propose separate alerts for limiter availability and policy rejection rate.','Provide the concurrent admission count, both outage outcomes, and a written policy defense tied to business cost and abuse risk.']
],extensions:['Add expiry/cleanup for inactive tenants and test capacity after eviction.','Implement conservative reservation transfers with fencing tokens.']},
P3:{file:'jobs',invariant:'Only the current unexpired claim token may commit a result. The local effect ledger and done state commit atomically; external side effects need their own idempotency boundary.',requirements:['Persist bounded queued/running/done/dead states and unique job identities.','Recover crashed workers through leases with fresh claim tokens, bounded retry backoff, and dead letters.','Stop claiming during graceful shutdown, back up with SQLite backup API, and verify restored state.'],architecture:'enqueue → durable queue → lease claim with token → handler → transactional local result + done; failures → delayed retry → dead letter at limit.',limits:'Local workers share one SQLite database. The effect ledger proves only effects stored in the same transaction. An email or payment API outside this database is not exactly-once by this mechanism.',milestones:[
['Claims, execution and recovery','Implement enqueue, claim and complete. Freeze time, claim a job, advance beyond its lease, and claim again. The second worker receives a different token. Reject completion from the first worker even though it once legitimately owned the job.','Worker A pauses beyond expiry while B reclaims. A resumes and attempts a stale commit. Checking only job ID would allow it; validate token, state and current lease within the commit transaction.','Demonstrate stale-worker rejection, current-worker success, and one durable local effect.'],
['Retries, dead letters and telemetry','Add exponential retry delays capped at sixty seconds and an explicit maximum attempt count. Preserve a bounded error description. Use the fake clock to show a failed job cannot be reclaimed before its available time.','A poison job must not circulate indefinitely or hide behind a growing backlog. Dead-letter after the configured attempt budget, and distinguish queued/running/dead counts.','Capture first failure → delayed retry → final dead letter and a state-count report. Explain retryability classification for real failures.'],
['Graceful stop and bounded workers','Add admission capacity and a worker drain loop with a stop event and maximum job count. A stop request prevents new claims while current work may finish. Define a termination grace period at least as long as bounded handler cleanup.','An unbounded queue moves overload into memory/storage and increases recovery time. A second enqueue into a full queue must fail explicitly without losing the accepted job.','Run a full-queue test and a stopped-worker test; then drain one unit and show the capacity becomes available.'],
['Chaos and restore handover','Exercise duplicate enqueue, conflicting payload reuse, expired claims and backup restore. Use SQLite backup rather than copying an open WAL database. Open the backup independently and check jobs and effects as one consistent state.','A backup file existing does not prove recoverability. Restore to a separate database and inspect a completed job and exactly one local effect before calling the drill successful.','Write a runbook with queue-depth thresholds, dead-letter triage, safe retry procedure, shutdown order and measured recovery evidence.']
],extensions:['Add an outbox and idempotent HTTP receiver to demonstrate cross-boundary effect handling.','Add lease renewal plus stale-token tests at the exact renewal boundary.']},
P4:{file:'chat',invariant:'Authorized messages commit before acknowledgement and have a monotonically increasing sequence within each room. Live delivery is a hint; a cursor can recover committed messages.',requirements:['Persist room membership, ordered message log, and sender-scoped idempotency keys.','Support reconnect via seq > cursor, independently of lost pub/sub notifications.','Use separate DB connections for concurrent workers and expiring presence that never grants authorization.'],architecture:'authenticated demo WebSocket → membership check → SQL append with room sequence → acknowledgement; live notification hints → reconnect query against authoritative log.',limits:'The supplied stdlib WebSocket scaffold supports bounded unfragmented text frames, ping/pong and close. Demo tokens are local test identities, not a production identity provider. Hub is an in-process lossy pub/sub stand-in shared by worker objects, not a multi-host broker.',milestones:[
['Persisted messaging on a transport scaffold','Fill in the Chat store behind serve_chat.py. Keep connection framing out of the milestone: the prepared harness implements the handshake and bounded masked text frames. Commit the room sequence and message together before returning the sequence.','An acknowledgement sent before commit can lose a message after the sender stops retrying. A retry must return the existing sequence for identical content, while changed content under the same key conflicts.','Send two messages, retry one, restart the store, and observe exactly two sequences in order.'],
['Reconnect and offline delivery','Implement a bounded keyset query using room and seq > cursor. Disable the hub for one committed message, reconnect from the last acknowledged sequence, and retrieve the missed item from storage.','Presence or socket connection status cannot prove delivery. Cursor advancement should occur after the client applies a message, with deduplication by room and sequence.','Show a missing live notification followed by successful cursor recovery with no fabricated delivery guarantee.'],
['Multiple workers and presence expiry','Create two worker objects sharing the same database and hub. Submit twenty messages concurrently and verify sequence uniqueness. Add heartbeat leases and remove stale presence at an exact fake-clock boundary.','Generating sequence numbers outside the append transaction creates duplicates or gaps caused by conflicting writers. Presence is eventually accurate and may remain visible until TTL expires.','Observe sequences 1 through 20 exactly once, plus online→offline after a ten-second heartbeat expiry.'],
['Disconnect, authorization and recovery','Test unauthorized send and read, conflicting retry payloads, and transport reconnect. The server determines sender identity from its validated demo token, not a user field in the JSON payload. State the production changes needed before exposure beyond loopback.','Never trust a supplied room cursor or user name as authorization. Repeat membership checks on each command and use the stored identity throughout.','Provide a denied read/write transcript, a real WebSocket reconnect test, and a recovery explanation grounded in the persistent log.']
],extensions:['Replace the Hub simulator with a broker adapter while retaining cursor recovery tests.','Add read-receipt semantics distinct from delivery acknowledgement and user presence.']},
P5:{file:'events',invariant:'Each accepted event has a stable ID and immutable payload. A projection update, deduplication marker, and checkpoint advance commit atomically within the teaching database.',requirements:['Partition events deterministically by account and order ingestion offsets within each partition.','Apply additive minor-unit deltas correctly even when event-time order differs from arrival order.','Recover checkpoints, rebuild a separate projection, upcast supported schema versions, and reconcile against the immutable source.'],architecture:'validated event → immutable partitioned SQL log → bounded consumer batch → atomic applied-ID + account total + checkpoint; replay writes a named shadow projection.',limits:'All log/projection state is in one SQLite authority. The transaction is not a promise of exactly-once external effects or a distributed stream processor. Late-event semantics here are additive totals, not event-time windows.',milestones:[
['Partitioned ingestion and replayable identity','Use SHA-256 of account to choose a fixed partition count. Assign increasing offsets transactionally. Repeat the same event ID and payload to obtain the original offset; reject a changed payload. Persist the partition count as immutable configuration.','Changing partition count in place can reorder an account and invalidate existing checkpoints. Require a migration instead of silently rehashing a durable log.','Show stable account affinity, increasing offsets, and duplicate ingest returning the original position.'],
['Projection, duplicate and late-event behavior','Maintain integer account totals. An event with an earlier event_time still changes the total once when it arrives. Store a deduplication marker and advance the partition checkpoint in the same transaction as the total.','A checkpoint committed ahead of a projection loses work; projection committed without dedupe can double-apply retries. Keep the transaction boundary explicit.','Apply +10 at time 200 and −3 at time 100, consume twice, and reconcile to exactly 7.'],
['Crash recovery and safe replay','Inject a failure after a projection write but before checkpoint persistence. Verify rollback, reopen the database, and consume again. Build a named shadow projection with its own checkpoints, leaving live data available.','Rebuilding live state by deleting it first creates an avoidable outage and makes validation difficult. Compare the completed shadow projection before any future cutover.','Show zero partial projection after the injected failure, correct recovery, and a successful independent replay reconciliation.'],
['Schema and backfill evidence','Accept v1 amount and v2 amount_minor_units as explicit schemas with integer money units. Reject unknown versions and same-ID payload conflicts. Recompute expected account sums from source events and compare derived totals.','A guessed default for an unknown schema can silently corrupt totals. Quarantine unsupported inputs upstream and make failure visible instead of treating them as zero.','Mix two supported versions, reject a future version, and report expected versus actual totals. Document the rollback condition for a shadow projection cutover.']
],extensions:['Add event-time windows, watermarks, and an explicit policy for late corrections.','Introduce a separate sink to show why cross-database checkpoints need idempotent effects.']},
P6:{file:'gateway',invariant:'Admission atomically reserves each tenant’s maximum output-unit budget before work starts. Completion, cancellation and failure release unused reservations and preserve per-request accounting.',requirements:['Expose a bounded streaming generator backed by an explicit local deterministic token stub.','Isolate tenant concurrency and output-unit budgets; reject reused request IDs rather than silently double-charge or replay incomplete streams.','Record delivery-unit counts, time to first delivered token, duration, and outcome; release reservations on every terminal path.'],architecture:'tenant + request ID → atomic concurrency/budget reservation → cancellable stub iterator → delivered token stream → finally release unused units + telemetry.',limits:'No AI model runs here. Stub tokens are illustrative output units, not tokenizer IDs, provider billing or measured inference throughput. Budgets are process-local. Deadline checks occur between cooperative stub tokens and cannot interrupt an arbitrary blocking provider call; real adapters need cancellable I/O and provider-side billing reconciliation.',milestones:[
['Contracts, stub and cancellable stream','Implement the generator contract and close propagation. Consume one token, then explicitly close the stream as a disconnected HTTP/SSE transport would. Use try/finally so provider cleanup and accounting run during generator cancellation.','A abandoned generator that remains referenced may retain a reservation. The transport adapter must close on disconnect; documentation and tests should show that ownership contract.','Observe one delivered token, cancelled outcome, zero active count, and charge of exactly one illustrative output unit.'],
['Tenant limits and budgets','Under a lock, reserve max_tokens and one concurrency slot before advancing the provider. Start a stream for Alice, reject her second concurrent stream, and allow Bob independently. Release unused budget when the stream ends.','Checking balance and decrementing in separate critical sections permits over-admission. Reserving only delivered tokens can also permit too many simultaneous future obligations.','Demonstrate tenant isolation and deterministic rejection when the requested ceiling exceeds remaining allowance.'],
['Provider errors, cancellation and telemetry','Inject a disconnect after one token and a provider delay past the deadline. Guarantee finally cleanup, distinguish provider_error from timeout/cancelled, and avoid automatic stream retries once output has been observed.','Retrying a partially delivered generation can duplicate or contradict visible output. State whether a client should start a new logical request instead of hiding the failure.','Verify no reservation leak after provider error or timeout, with accurate emitted-unit count and terminal status.'],
['Load/fault and cost evidence','Run ten deterministic stub requests and total the output units. Compare first-token latency with overall duration. Label cost units and timing as simulation output; do not translate them into GPU capacity or vendor currency without a real measurement model.','Counting only completed requests conceals partial outputs and cancelled work. Include those outcomes separately and explain that real provider billing may count tokens not delivered to the client.','Provide per-request telemetry, 30 emitted units across ten runs, 0.02-second first-token simulation, and an explicit uncertainty/limitation paragraph.']
],extensions:['Add a durable reservation ledger and crash reconciliation with conservative orphan handling.','Add a real cancellable HTTP adapter against a local fake SSE server, without a paid provider.']},
};
mkdirSync(resolve(root,'content/projects'),{recursive:true});
for(const source of manifest.projects){
 const spec=specs[source.id];const milestones=source.milestones.map((m,i)=>({ ...m,title:manifest.lessons.find(l=>l.id===m.lessonId).title,focus:spec.milestones[i][0],task:spec.milestones[i][1],failureInjection:spec.milestones[i][2],evidence:spec.milestones[i][3],minutes:60,budget:{brief:10,implementation:25,tests:15,evidence:10},testCommand:`py -3 -m unittest discover -s projects/tests -p test_projects.py -k ${source.id}_${i+1} -v`,stopCondition:'Stop when the focused deterministic test passes and the stated evidence is recorded. Extensions are separate practice.'}));
 const output={...source,version:1,status:'reference-tested',authorship:'original prepared teaching implementation; curriculum names and milestone IDs source-derived',invariant:spec.invariant,requirements:spec.requirements,architecture:spec.architecture,limitations:spec.limits,milestones,extensions:spec.extensions,learnerFile:`projects/learner/${spec.file}.py`,referenceFile:`projects/reference/${spec.file}.py`,instructionsFile:`projects/${source.id}.md`,testFile:'projects/tests/test_projects.py',referenceReveal:'Explicit reveal in the academy; reference source also remains inspectable on disk. Educational spoiler control, not secure examination.'};
 writeFileSync(resolve(root,`content/projects/${source.id}.json`),JSON.stringify(output,null,2)+'\n');
 let md=`# ${source.id} — ${source.title}\n\n${spec.invariant}\n\nThis prepared teaching lab uses Python 3.11+ standard-library modules. It is separate from the academy learner database. Read [the shared lab instructions](README.md) before running commands. Reference tests have been executed; learner TODOs are intentional work.\n\n## Requirements and mechanism\n\n${spec.requirements.map(t=>`- ${t}`).join('\n')}\n\n${spec.architecture}\n\n**Limits:** ${spec.limits}\n\nLearner source: [${spec.file}.py](learner/${spec.file}.py). Reference source: [reveal after attempting](reference/${spec.file}.py). Tests: [test_projects.py](tests/test_projects.py).\n\n`;
 for(const m of milestones)md+=`## Milestone ${m.number} · Lesson ${m.lessonId} · ${m.focus}\n\nSource activity: ${m.title}\n\n${m.task}\n\n**Failure injection:** ${m.failureInjection}\n\n**Acceptance evidence:** ${m.evidence}\n\nBudget: 10 minutes reading and prediction, 25 implementation, 15 focused testing, 10 recording evidence. Setup is separate. Stop after the check and evidence; extensions are optional.\n\n\`\`\`powershell\n${m.testCommand}\n\`\`\`\n\n`;
 md+=`## Evidence report\n\nRecord the invariant, exact command, expected and actual result, injected failure, recovery action, and one alternative with its tradeoff. Label simulated timestamps and locally measured operation counts. Do not infer production throughput or cross-host guarantees from these tests.\n\n## Optional additional practice\n\n${spec.extensions.map(t=>`- ${t}`).join('\n')}\n`;
 writeFileSync(resolve(root,`projects/${source.id}.md`),md);
}
console.log('Wrote six original project specifications and 24 source-mapped milestones.');
