import {chromium,expect} from '@playwright/test';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {startServer} from '../server/index.js';
const output=resolve('artifacts/diagram-readability');mkdirSync(output,{recursive:true});
const app=await startServer({root:resolve('.'),dataDir:mkdtempSync(resolve(output,'controls-data-')),port:0,quiet:true});
const origin=`http://127.0.0.1:${app.port}`;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors:string[]=[],external:string[]=[],checks:string[]=[];
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin&&!['data:','blob:'].includes(u.protocol)){external.push(u.href);return route.abort();}return route.continue();});
try{
 await page.goto(`${origin}/#guide/what-is-system-design`);
 const card=page.locator('.diagram-card').filter({hasText:'Choose a part because of a user need'});
 await expect(card).toHaveAttribute('data-rendered','true');
 await expect(card.locator('foreignObject')).toHaveCount(0);
 await page.getByRole('button',{name:'Switch to dark theme',exact:true}).click();
 await card.locator('.diagram-text summary').click();
 await expect(card.locator('.diagram-text ul')).toContainText('Need the same app rules on both devices');
 await expect(card.locator('.diagram-text ul')).toContainText('Need to find a saved note later');
 await card.locator('.diagram-text summary').click();checks.push('The reported diagram uses native SVG labels and exposes the complete original wording in its text alternative.');
 const before=await card.locator('.diagram-svg svg').evaluate(svg=>svg.getBoundingClientRect().width);
 await card.getByRole('button',{name:'Zoom in',exact:true}).click();
 await expect(card.locator('.zoom-value')).toHaveText('120%');
 expect(await card.locator('.diagram-svg svg').evaluate(svg=>svg.getBoundingClientRect().width)).toBeGreaterThan(before);
 await card.getByRole('button',{name:'Zoom out',exact:true}).click();
 await card.getByRole('button',{name:'Expand diagram',exact:true}).click();
 await expect(card).toHaveAttribute('role','dialog');
 await card.screenshot({path:resolve(output,'reported-diagram-expanded-dark.png')});
 await page.keyboard.press('Escape');await expect(card).not.toHaveAttribute('role','dialog');
 await expect(card.getByRole('button',{name:'Expand diagram',exact:true})).toBeFocused();checks.push('Zoom, expansion, Escape, and keyboard focus return work in the production page.');
 await page.setViewportSize({width:390,height:844});
 const canvas=card.locator('.diagram-canvas');await canvas.focus();await page.keyboard.press('ArrowRight');
 await expect.poll(()=>canvas.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2)).toBe(false);
 await card.screenshot({path:resolve(output,'reported-diagram-mobile-dark.png')});checks.push('Narrow-screen diagrams can be panned by keyboard without overflowing the page.');
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(`${origin}/#guide/reliability-controls`);
 // Resolve by its canonical ID-independent title rather than a fixed page position.
 const diagrams=page.locator('.diagram-card');await expect(diagrams).toHaveCount(2);
 await expect(diagrams.last()).toHaveAttribute('data-rendered','true');
 const target=await diagrams.evaluateAll(cards=>cards.map((card,index)=>({index,height:(card.querySelector('svg') as SVGSVGElement).viewBox.baseVal.height})).sort((a,b)=>b.height-a.height)[0].index);
 await diagrams.nth(target).evaluate(element=>{document.body.replaceChildren(element.cloneNode(true));document.documentElement.dataset.theme='light';});
 await page.emulateMedia({media:'print'});
 await expect(page.locator('.diagram-print-labels')).toBeVisible();
 expect(await page.locator('.diagram-svg svg').evaluate(svg=>svg.getBoundingClientRect().height)).toBeLessThan(682);
 await page.pdf({path:resolve(output,'tall-diagram.pdf'),format:'A4',printBackground:true,margin:{top:'14mm',bottom:'14mm',left:'14mm',right:'14mm'}});
 checks.push('The tallest diagram fits inside print height limits; all original labels also print as readable text.');
 expect(errors).toEqual([]);expect(external).toEqual([]);
 writeFileSync(resolve(output,'controls-report.json'),JSON.stringify({passed:true,checks,errors,externalRequests:external},null,2)+'\n');console.log(JSON.stringify({passed:true,checks},null,2));
}finally{await browser.close();await app.close();}
