import {readFileSync,existsSync,writeFileSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const path=JSON.parse(readFileSync('content/learning-path.json','utf8')),ids=new Set(),errors=[],records=[];
assert.equal(path.stages.length,6);assert.equal(path.weeks.length,24);assert.equal(path.weeks.flatMap(w=>w.days).length,152);
for(const week of path.weeks){assert([2,4,5].includes(week.guides.length));assert.equal(week.days.length,week.guides.length===5?9:week.guides.length===4?7:5);assert.equal(new Set(week.days.map(d=>d.day)).size,week.days.length);for(const meta of week.guides){assert(!ids.has(meta.id));ids.add(meta.id);const file=`content/guides/${meta.id}.json`;if(!existsSync(file)){records.push({id:meta.id,week:week.number,state:'not-authored'});continue;}try{const raw=readFileSync(file,'utf8'),g=JSON.parse(raw);assert.equal(g.id,meta.id);assert.equal(g.week,week.number);assert.equal(g.title,meta.title);assert(g.objectives.length>=3);assert(g.terms.length>=3);assert(g.sections.length>=4);const words=g.sections.map(s=>s.markdown).join(' ').split(/\s+/).length;assert(words>=550,'Body below structural minimum; editorial quality must be reviewed separately.');assert(new Set(g.sections.map(s=>s.id)).size===g.sections.length);assert(g.diagrams.length>=1);for(const d of g.diagrams){assert(d.source&&d.caption&&d.steps.length>=3);assert(!d.sectionId||g.sections.some(s=>s.id===d.sectionId),'Unknown diagram section');}assert(g.exercise.solution.length>=150);assert(g.questions.length>=5);assert(g.questions.filter(q=>q.type==='choice'||q.type==='numeric').length>=3);for(const q of g.questions){assert(q.explanation&&q.answer!==undefined);if(q.type==='choice')assert(q.options.includes(q.answer));if(q.type==='numeric')assert(q.unit&&typeof q.answer==='number');}assert(g.flashcards.length>=5);assert(g.sources.length>=1);records.push({id:g.id,week:g.week,state:'drafted',words,diagrams:g.diagrams.length,sha256:createHash('sha256').update(raw).digest('hex')});}catch(error){errors.push(`${meta.id}: ${error.message}`);}}}
assert.equal(ids.size,76);for(const week of path.weeks)for(const day of week.days)assert(ids.has(day.guideId));
for(const resource of path.resources){assert(/^https?:\/\//.test(resource.url));assert(resource.provider&&resource.why&&resource.checkedAt);}
const missing=records.filter(x=>x.state==='not-authored').map(x=>x.id);if(process.argv.includes('--complete')&&missing.length)errors.push(`${missing.length} planned chapters are not authored.`);
const result={generatedAt:new Date().toISOString(),planned:76,authored:76-missing.length,missing,words:records.reduce((n,r)=>n+(r.words||0),0),errors,records,limitations:['Structural checks cannot establish teaching quality. Original explanations and critical guarantees require editorial review.']};mkdirSync('artifacts',{recursive:true});writeFileSync('artifacts/guide-validation.json',JSON.stringify(result,null,2)+'\n');writeFileSync('content/guide-status.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({planned:76,authored:result.authored,words:result.words,missing,errors},null,2));if(errors.length)process.exitCode=1;
