import {useEffect, useRef, useState, type ReactNode, type RefObject, type CSSProperties} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeHighlight from 'rehype-highlight';
import {renderStudyDiagram} from './diagram-rendering';
import './diagrams.css';
import {Check, Copy, Maximize2, Minus, Plus, X, ChevronLeft, ChevronRight} from 'lucide-react';
import type {RecordData} from './api';

export function Badge({children, tone='neutral'}:{children:ReactNode;tone?:string}) {return <span className={`badge ${tone}`}>{children}</span>;}
export function Empty({icon, title, children}:{icon?:ReactNode;title:string;children:ReactNode}) {return <div className="empty-state">{icon}<h3>{title}</h3><div>{children}</div></div>;}
export function PageTitle({eyebrow,title,children,action}:{eyebrow:string;title:string;children?:ReactNode;action?:ReactNode}) {return <header className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children && <p className="intro">{children}</p>}</div>{action}</header>;}
export function CopyButton({text,label='Copy'}:{text:string;label?:string}) {const [copied,setCopied]=useState(false);return <button className="button subtle compact" onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setCopied(false);}}}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':label}</button>;}
function CodeBlock({children}:{children?:ReactNode}) {const ref=useRef<HTMLPreElement>(null);return <div className="code-wrap"><CopyButton text={ref.current?.textContent||String((children as any)?.props?.children||'')}/><pre ref={ref}>{children}</pre></div>;}
export function Prose({text}:{text:any}) {if(!text)return null;return <div className="prose"><Markdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]} components={{pre:({children})=><CodeBlock>{children}</CodeBlock>,a:({href,children})=><a href={href} target={href?.startsWith('http')?'_blank':undefined} rel="noreferrer">{children}</a>}}>{typeof text==='string'?text:JSON.stringify(text,null,2)}</Markdown></div>;}
export function useDialogFocus(ref:RefObject<HTMLElement|null>,active:boolean,onEscape?:()=>void){useEffect(()=>{if(!active)return;const previous=document.activeElement as HTMLElement|null;const selector='button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]';const first=ref.current?.querySelector<HTMLElement>(selector);first?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){onEscape?.();return;}if(event.key!=='Tab')return;const items=Array.from(ref.current?.querySelectorAll<HTMLElement>(selector)||[]).filter(item=>item.getClientRects().length);if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[active]);}
let diagramSequence=0;
export function Diagram({diagram}:{diagram:RecordData}) {
 const [svg,setSvg]=useState(''),[error,setError]=useState(''),[zoom,setZoom]=useState(1),[expanded,setExpanded]=useState(false),[step,setStep]=useState(-1);
 const [size,setSize]=useState({width:640,height:400}),[availableWidth,setAvailableWidth]=useState(640),[labels,setLabels]=useState<string[]>([]);
 const figure=useRef<HTMLElement>(null),canvas=useRef<HTMLDivElement>(null);useDialogFocus(figure,expanded,()=>setExpanded(false));
 useEffect(()=>{let cancelled=false;setSvg('');setError('');setLabels([]);setZoom(1);setStep(-1);renderStudyDiagram(`diagram-${++diagramSequence}`,diagram.source||diagram.mermaid||'').then(result=>{if(!cancelled){setSvg(result.svg);setSize({width:result.width,height:result.height});setLabels(result.labels);}}).catch(err=>{if(!cancelled)setError(String(err));});return()=>{cancelled=true;};},[diagram.source,diagram.mermaid]);
 useEffect(()=>{const element=canvas.current;if(!element)return;const observer=new ResizeObserver(([entry])=>setAvailableWidth(entry.contentRect.width));observer.observe(element);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!expanded)return;const listener=(event:KeyboardEvent)=>{if(event.key==='Escape')setExpanded(false);};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[expanded]);
 const steps=diagram.steps||[];
 useEffect(()=>{const root=figure.current;if(!root)return;root.querySelectorAll('.step-active,.step-muted').forEach(node=>node.classList.remove('step-active','step-muted'));if(step<0)return;const entry=steps[step];const edges=Array.from(root.querySelectorAll('.messageLine0,.messageLine1,.edgePaths .flowchart-link'));const texts=Array.from(root.querySelectorAll('.messageText,.edgeLabels .edgeLabel'));if(Array.isArray(entry?.activeEdges)){edges.forEach((edge,index)=>edge.classList.add(entry.activeEdges.includes(index)?'step-active':'step-muted'));texts.forEach((text,index)=>text.classList.add(entry.activeEdges.includes(index)?'step-active':'step-muted'));}if(entry?.activeNodes){root.querySelectorAll('.node').forEach(node=>node.classList.add(entry.activeNodes.some((id:string)=>node.id.includes(`-${id}-`))?'step-active':'step-muted'));}},[step,svg]);
 const displayWidth=Math.max(Math.min(availableWidth,size.width),size.width*.875)*zoom;
 const needsScroll=displayWidth>availableWidth+2||size.height*displayWidth/size.width>620;
 return <figure ref={figure} className={`diagram-card ${expanded?'expanded':''}`} data-rendered={!!svg} role={expanded?'dialog':undefined} aria-modal={expanded?true:undefined} aria-label={diagram.title}>
 <div className="diagram-header"><div><span className="eyebrow">SYSTEM VIEW</span><h4>{diagram.title||'Mechanism diagram'}</h4></div><div className="button-row"><button className="icon-button" aria-label="Zoom out" onClick={()=>setZoom(Math.max(.5,zoom-.2))}><Minus size={16}/></button><span className="zoom-value">{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" onClick={()=>setZoom(Math.min(3,zoom+.2))}><Plus size={16}/></button><button className="icon-button" aria-label={expanded?'Close expanded diagram':'Expand diagram'} onClick={()=>setExpanded(!expanded)}>{expanded?<X size={16}/>:<Maximize2 size={16}/>}</button></div></div>
 <div ref={canvas} className="diagram-canvas" tabIndex={0} role="region" aria-label={`${diagram.title||'Diagram'} — scrollable illustration`}>{error?<div className="notice warning">Diagram could not render. Read its explanation below.<details><summary>Editable source</summary><pre>{diagram.source}</pre></details></div>:<div className="diagram-svg" style={{width:displayWidth,minWidth:displayWidth,'--diagram-width':`${size.width}px`} as CSSProperties} dangerouslySetInnerHTML={{__html:svg}}/>}</div>
 {needsScroll&&<p className="diagram-scroll-hint">Scroll inside the diagram, or expand it for more space. A text version is below.</p>}
 <figcaption>{diagram.caption||diagram.description}</figcaption>{steps.length>0&&<div className="diagram-steps"><div className="button-row"><button className="icon-button" aria-label="Previous step" disabled={step<0} onClick={()=>setStep(step-1)}><ChevronLeft size={17}/></button><span className="eyebrow">{step<0?'FOLLOW THE FLOW':`STEP ${step+1} OF ${steps.length}`}</span><button className="icon-button" aria-label="Next step" disabled={step===steps.length-1} onClick={()=>setStep(step+1)}><ChevronRight size={17}/></button></div><p aria-live="polite">{step<0?'Step through the mechanism, one transition at a time.':typeof steps[step]==='string'?steps[step]:steps[step].text||steps[step].description||steps[step].explanation}</p></div>}
 {steps.length>0&&<ol className="diagram-print-steps">{steps.map((entry:any,index:number)=><li key={index}>{typeof entry==='string'?entry:entry.text||entry.description||entry.explanation}</li>)}</ol>}
 {labels.length>0&&<div className="diagram-print-labels"><strong>Diagram labels</strong><ul>{labels.map((label,index)=><li key={index}>{label}</li>)}</ul></div>}
 <details className="diagram-text"><summary>Read diagram as text</summary><p>{diagram.caption||diagram.description}</p>{steps.length>0&&<ol>{steps.map((entry:any,index:number)=><li key={index}>{typeof entry==='string'?entry:entry.text||entry.description||entry.explanation}</li>)}</ol>}{labels.length>0&&<><p><strong>Labels in this diagram</strong></p><ul>{labels.map((label,index)=><li key={index}>{label}</li>)}</ul></>}</details>
 </figure>;
}

export function SkillGraph(){return <svg className="hero-graph" viewBox="0 0 400 260" fill="none" aria-hidden="true"><defs><pattern id="dotGrid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#bcd4bc" opacity=".16"/></pattern></defs><rect width="400" height="260" fill="url(#dotGrid)"/><path d="M40 128H113M177 128H245M308 78H337V178H308M277 96V110M277 146V160" stroke="#b8ccad" strokeWidth="1.5"/><path d="M145 160V204H278V190" stroke="#b8ccad" strokeWidth="1.5" strokeDasharray="4 5"/><rect x="28" y="108" width="48" height="40" rx="10" fill="#315b4e" stroke="#88a590"/><path d="M43 125l-5 4 5 4m17-8 5 4-5 4m-7-10-4 19" stroke="#d8e7bd" strokeWidth="1.6"/><rect x="111" y="96" width="68" height="65" rx="12" fill="#cbdcab"/><rect x="129" y="114" width="31" height="8" rx="2" stroke="#2b5948"/><rect x="129" y="134" width="31" height="8" rx="2" stroke="#2b5948"/><circle cx="153" cy="118" r="1.5" fill="#2b5948"/><circle cx="153" cy="138" r="1.5" fill="#2b5948"/><rect x="245" y="54" width="65" height="45" rx="10" fill="#315b4e" stroke="#88a590"/><path d="M263 76h28m-24-7h20m-20 14h20" stroke="#d8e7bd" strokeWidth="1.5"/><rect x="245" y="110" width="65" height="38" rx="9" fill="#315b4e" stroke="#88a590"/><path d="M263 126h28m-24 7h20" stroke="#d8e7bd" strokeWidth="1.5"/><ellipse cx="277" cy="166" rx="30" ry="9" fill="#315b4e" stroke="#88a590"/><path d="M247 167v19c0 12 60 12 60 0v-19" fill="#315b4e" stroke="#88a590"/><path d="M247 175c0 12 60 12 60 0" stroke="#88a590"/><circle cx="211" cy="128" r="4" fill="#cedead"/><circle cx="145" cy="203" r="4" fill="#cedead"/><text x="112" y="76" fill="#c6d6c0" fontSize="9" fontFamily="monospace" letterSpacing="1.5">THINK IN SYSTEMS</text><text x="238" y="226" fill="#9cb39d" fontSize="9" fontFamily="monospace">simple → understood → scaled</text></svg>}
